#!/bin/bash
# setup-cpuminer-blackshirt.sh
# One-file installer for cpuminer-blackshirt x86 Linux
# Downloads binary, filter, asks config, generates start script
# Blackshirt Crypto — blkshirtpool.com

INSTALL_DIR=~/cpuminer-blackshirt
REPO="https://github.com/blackshirt-crypto/cpuminer-linux-blackshirt/releases/download/v26.2"
BINARY="cpuminer-x86-v26.2"

clear
echo ""
echo "  ╔══════════════════════════════════════╗"
echo "  ║   cpuminer-blackshirt  x86 Setup     ║"
echo "  ║   Blackshirt Crypto                  ║"
echo "  ╚══════════════════════════════════════╝"
echo ""

mkdir -p "$INSTALL_DIR"
echo "[1/4] Created install directory: $INSTALL_DIR"
echo ""

echo "[2/4] Downloading cpuminer-blackshirt binary..."
curl -L --progress-bar -o "$INSTALL_DIR/cpuminer-blackshirt" "$REPO/$BINARY"
if [ $? -ne 0 ] || [ ! -s "$INSTALL_DIR/cpuminer-blackshirt" ]; then
    echo "ERROR: Binary download failed."
    exit 1
fi
chmod +x "$INSTALL_DIR/cpuminer-blackshirt"
echo "Binary downloaded."
echo ""

echo "[3/4] Downloading output filter..."
curl -L --progress-bar -o "$INSTALL_DIR/filter.py" "$REPO/filter.py"
if [ $? -ne 0 ] || [ ! -s "$INSTALL_DIR/filter.py" ]; then
    echo "ERROR: Filter download failed."
    exit 1
fi
chmod +x "$INSTALL_DIR/filter.py"
echo "Filter downloaded."
echo ""

echo "[4/4] Downloading reconfigure.sh..."
curl -L --progress-bar -o "$INSTALL_DIR/reconfigure.sh" "$REPO/reconfigure.sh"
chmod +x "$INSTALL_DIR/reconfigure.sh"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Mining Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Choose your mining algorithm below."
echo "  Enter the TYPE shown — not the coin ticker."
echo "  Example: type 'civiclight' for CivicNet, not 'CIVIC'"
echo ""
echo "  TYPE           COIN"
echo "  ─────────────────────────────────────"
echo "  civiclight     CivicNet (CIVIC)"
echo "  yespowerr16    Yenten (YTN)"
echo "  yescryptr16    Fennec (FNNC)"
echo "  yespower       various yespower coins"
echo "  sha256d        various SHA-256d coins"
echo "  scrypt         various scrypt coins"
echo "  whirlpool      CapStash (CAP)"
echo ""
read -p "  Algorithm type: " ALGO

if [ -z "$ALGO" ]; then
    echo "ERROR: Algorithm is required."
    exit 1
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Pool Configuration"
echo "  Format: stratum+tcp://HOSTNAME:PORT"
echo "  Example: stratum+tcp://blkshirtpool.com:4353"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
read -p "  Primary pool: " POOL

if [ -z "$POOL" ]; then
    echo "ERROR: Primary pool is required."
    exit 1
fi

read -p "  Backup pool (optional, press Enter to skip): " POOL2

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Wallet & Worker"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
read -p "  Wallet address: " WALLET

if [ -z "$WALLET" ]; then
    echo "ERROR: Wallet address is required."
    exit 1
fi

read -p "  Worker name (optional, press Enter to skip): " WORKER
if [ -n "$WORKER" ]; then
    WORKER_STRING=".$WORKER"
else
    WORKER_STRING=""
fi

read -p "  Password (default: x, press Enter to use x): " PASS
PASS=${PASS:-x}

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Thread Selection"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
MAX_THREADS=$(nproc)
echo "  Your device has $MAX_THREADS CPU cores available."
echo "  Tip: on big.LITTLE phones, fewer threads often = more hash"
echo "  Recommended: test 4, 6, and 8 to find your sweet spot"
echo ""
while true; do
    read -p "  Threads (1-$MAX_THREADS): " THREADS
    if [[ "$THREADS" =~ ^[0-9]+$ ]] && [ "$THREADS" -ge 1 ] && [ "$THREADS" -le "$MAX_THREADS" ]; then
        break
    fi
    echo "  Please enter a number between 1 and $MAX_THREADS."
done

# Generate start script
SAVEFILE="$INSTALL_DIR/start-${ALGO}.sh"

cat > "$SAVEFILE" << EOF
#!/bin/bash
# cpuminer-blackshirt — ${ALGO}
# Generated by setup-cpuminer-blackshirt.sh
# Run ~/cpuminer-blackshirt/reconfigure.sh to change settings
ALGO=${ALGO}
POOL=${POOL}
POOL2=${POOL2}
WALLET=${WALLET}${WORKER_STRING}
PASS=${PASS}
THREADS=${THREADS}
INSTALL_DIR=~/cpuminer-blackshirt
MINER="\$INSTALL_DIR/cpuminer-blackshirt"
FILTER="\$INSTALL_DIR/filter.py"

# Note: cpuminer-opt does not support multiple pools natively
# POOL2 is saved for reference but not passed to the miner
POOL_ARGS="-o \$POOL"

trap "echo ''; echo 'Miner stopped.'; exit 0" INT TERM

"\$MINER" -a "\$ALGO" \$POOL_ARGS -u "\$WALLET" -p "\$PASS" -t "\$THREADS" 2>&1 | python3 "\$FILTER" "\$ALGO" "\$POOL" "\$THREADS"
EOF

chmod +x "$SAVEFILE"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Setup Complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Installed to: $INSTALL_DIR"
echo "    cpuminer-blackshirt  — miner binary"
echo "    filter.py            — output formatter"
echo "    start-${ALGO}.sh     — your start script"
echo "    reconfigure.sh       — change settings later"
echo ""
echo "  To mine again:  ~/cpuminer-blackshirt/start-${ALGO}.sh"
echo "  To change:      ~/cpuminer-blackshirt/reconfigure.sh"
echo ""
echo "  Starting miner now..."
echo ""
exec "$SAVEFILE"
