#!/bin/bash
# cpuminer-blackshirt universal start script
# Asks mining config questions, saves as start-{algo}.sh, then mines
# with a clean refreshing dashboard display
# Blackshirt Crypto — blkshirtpool.com

MINER=~/cpuminer-blackshirt

if [ ! -f "$MINER" ]; then
    echo "ERROR: cpuminer-blackshirt not found at $MINER"
    echo "Download it first:"
    echo "  curl -L -o ~/cpuminer-blackshirt https://github.com/blackshirt-crypto/cpuminer-android-blackshirt/releases/latest/download/cpuminer-arm64-v26.2"
    echo "  chmod +x ~/cpuminer-blackshirt"
    exit 1
fi

echo ""
echo "  cpuminer-blackshirt — Mining Setup"
echo "  =================================="
echo ""
echo "Supported algorithms:"
echo "  civiclight   - CivicNet (CIVIC)"
echo "  yespowerr16  - Yenten (YTN)"
echo "  yescryptr16  - Fennec (FNNC)"
echo "  yespower     - Small yespower coins"
echo "  sha256d      - Small SHA-256d coins"
echo "  scrypt       - Small scrypt coins"
echo "  whirlpool    - CapStash (CAP)"
echo ""
read -p "Algorithm: " ALGO

if [ -z "$ALGO" ]; then
    echo "ERROR: Algorithm is required."
    exit 1
fi

echo ""
read -p "Pool address (e.g. stratum+tcp://blkshirtpool.com:4353): " POOL

if [ -z "$POOL" ]; then
    echo "ERROR: Pool address is required."
    exit 1
fi

echo ""
read -p "Wallet address: " WALLET

if [ -z "$WALLET" ]; then
    echo "ERROR: Wallet address is required."
    exit 1
fi

echo ""
read -p "Worker name (optional, press Enter to skip): " WORKER

if [ -n "$WORKER" ]; then
    WORKER_STRING=".$WORKER"
else
    WORKER_STRING=""
fi

echo ""
read -p "Password (default: x, press Enter to use x): " PASS
PASS=${PASS:-x}

echo ""
MAX_THREADS=$(nproc)
echo "Your device has $MAX_THREADS CPU cores available."
while true; do
    read -p "Number of threads to use (1-$MAX_THREADS): " THREADS
    if [[ "$THREADS" =~ ^[0-9]+$ ]] && [ "$THREADS" -ge 1 ] && [ "$THREADS" -le "$MAX_THREADS" ]; then
        break
    fi
    echo "Please enter a number between 1 and $MAX_THREADS."
done

# Save start script
SAVEFILE=~/start-${ALGO}.sh

cat > "$SAVEFILE" << EOF
#!/bin/bash
# cpuminer-blackshirt — $ALGO
# Generated by start.sh — run ~/reconfigure.sh to change settings
ALGO=$ALGO
POOL=$POOL
WALLET=${WALLET}${WORKER_STRING}
PASS=$PASS
THREADS=$THREADS
EOF

cat >> "$SAVEFILE" << 'LAUNCHEOF'

MINER=~/cpuminer-blackshirt
LOG=/tmp/cpuminer-${ALGO}.log
> "$LOG"

"$MINER" -a "$ALGO" -o "$POOL" -u "$WALLET" -p "$PASS" -t "$THREADS" 2>&1 | tee -a "$LOG" &
MINER_PID=$!

trap "kill $MINER_PID 2>/dev/null; echo ''; echo 'Miner stopped.'; exit 0" INT TERM

sleep 3

while kill -0 $MINER_PID 2>/dev/null; do
    clear
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  cpuminer-blackshirt  |  algo: $ALGO"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  Pool:    $POOL"
    echo "  Wallet:  ${WALLET:0:20}..."
    echo "  Threads: $THREADS"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

    HASHRATE=$(grep -oE '\([0-9]+\.[0-9]+h/s\)' "$LOG" | tail -1 | tr -d '()hs/')
    ACCEPTED=$(grep 'Accepted' "$LOG" | tail -1 | awk '{print $3}')
    REJECTED=$(grep 'Rejected' "$LOG" | tail -1 | awk '{print $3}')
    RATIO=$(grep 'Accepted' "$LOG" | tail -1 | grep -oE '[0-9]+\.[0-9]+%')
    TEMP=$(grep -oE 'curr [0-9]+ C' "$LOG" | tail -1 | grep -oE '[0-9]+')
    BLOCK=$(grep -oE 'New Block [0-9]+' "$LOG" | tail -1 | grep -oE '[0-9]+')
    SHARERATE=$(grep 'Share rate' "$LOG" | tail -1 | awk '{print $3}')
    TTF=$(grep -oE 'Share [0-9]+[ms][0-9]*[ms]*' "$LOG" | tail -1 | sed 's/Share //')

    if grep -q 'Stratum connection established' "$LOG" && ! grep -q 'connection failed\|connection reset' <(tail -5 "$LOG"); then
        STATUS="Connected"
    else
        STATUS="Connecting..."
    fi

    echo "  Status:   $STATUS"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    printf "  Hashrate: %-15s CPU Temp: %s C\n" "${HASHRATE:--.--} H/s" "${TEMP:---}"
    printf "  Accepted: %-15s Rejected: %s\n" "${ACCEPTED:-0}" "${REJECTED:-0}"
    printf "  Accept %%: %-15s Share/min: %s\n" "${RATIO:----}" "${SHARERATE:----}"
    printf "  Next share: %-13s Block:    %s\n" "${TTF:----}" "${BLOCK:----}"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  Press Ctrl+C to stop"
    echo ""

    sleep 15
done

echo "Miner process ended."
LAUNCHEOF

chmod +x "$SAVEFILE"

echo ""
echo "Config saved as $SAVEFILE"
echo "To mine again: $SAVEFILE"
echo "To change settings: ~/reconfigure.sh"
echo ""
echo "Starting miner..."
echo ""
exec "$SAVEFILE"
